import 'package:flutter/material.dart';

const List data =[
  ["Mouse","15","lib/images/mouse.png",Colors.green,'This ultra-slim optical mouse of Nedis is compact and fits comfortably in your hand. Just plug the cable of your mouse to the USB port of your PC or notebook to enjoy fast, smooth and accurate navigation. With a resolution of 1000 dpi, even the smallest movements are registered. Due to the ergonomic design, this mouse is appropriate for both left- and right-handed users. The Nedis ultra-slim optical mouse comes in four different colours.'],
  ["HeadPhone","59","lib/images/headphone.png",Colors.grey,'Double-ear standard headset. High quality dynamic cardioid microphone. High ambient-noise attenuation headphones. Microphone: 300Hz – 20kHz frequency response. Headphone: 40Hz – 20kHz frequency response. Cushioned with soft leatherette padding. Flexible gooseneck microphone positioning.'],
  ["MacBook","1699","lib/images/mac.png",Colors.amber,'At the WWDC 2022 event, Apple unveiled its new MacBook Pro 13-inch notebook powered by the Apple M2 chip. It features the same design as the 2021 MacBook Pro, with a TouchBar-equipped keyboard deck, screen bezels, and an aluminum chassis. The difference is the aforementioned M2 processor, which is expected to make multitasking and working with demanding tasks considerably smooth and fast.'],
  ["KeyBoard","29","lib/images/keyboard.png",Colors.pink,'A wireless Keyboard is an electronic keyboard that makes use of technologies like radio frequency (RF) technologies such as WiFi and Bluetooth or infrarot (IR) technologies to connect with phones, tablets or laptops. These days Wireless keyboards currently available with a wireless mouse along. Infrarot based wireless keyboards use light waves to relay signals to other infrarot computers. However, a wireless keyboard works on radio frequency technologies by means of a pulse from 27 MHz up to 2.4 GHz.'],
  ["SmartWatch","149","lib/images/smartwatch.png",Colors.blue,'Water Resistant	Yes Water Resistant Certificate	5ATM Scratch Resistant	Yes Meters and sensors	Heart Rate Monitor, SpO2 (Blood Oxygen) Monitor, Blood Pressure Monitor, Calorie Count, Step Count, Sleep Monitor Extra Features	Alarm Clock, Stopwatch, Timer, Reminder'],
  ["Mouse","15","lib/images/mouse.png",Colors.green,'This ultra-slim optical mouse of Nedis is compact and fits comfortably in your hand. Just plug the cable of your mouse to the USB port of your PC or notebook to enjoy fast, smooth and accurate navigation. With a resolution of 1000 dpi, even the smallest movements are registered. Due to the ergonomic design, this mouse is appropriate for both left- and right-handed users. The Nedis ultra-slim optical mouse comes in four different colours.'],
  ["HeadPhone","59","lib/images/headphone.png",Colors.grey,'Double-ear standard headset. High quality dynamic cardioid microphone. High ambient-noise attenuation headphones. Microphone: 300Hz – 20kHz frequency response. Headphone: 40Hz – 20kHz frequency response. Cushioned with soft leatherette padding. Flexible gooseneck microphone positioning.'],
  ["MacBook","1699","lib/images/mac.png",Colors.amber,'At the WWDC 2022 event, Apple unveiled its new MacBook Pro 13-inch notebook powered by the Apple M2 chip. It features the same design as the 2021 MacBook Pro, with a TouchBar-equipped keyboard deck, screen bezels, and an aluminum chassis. The difference is the aforementioned M2 processor, which is expected to make multitasking and working with demanding tasks considerably smooth and fast.'],
  ["KeyBoard","29","lib/images/keyboard.png",Colors.pink,'A wireless Keyboard is an electronic keyboard that makes use of technologies like radio frequency (RF) technologies such as WiFi and Bluetooth or infrarot (IR) technologies to connect with phones, tablets or laptops. These days Wireless keyboards currently available with a wireless mouse along. Infrarot based wireless keyboards use light waves to relay signals to other infrarot computers. However, a wireless keyboard works on radio frequency technologies by means of a pulse from 27 MHz up to 2.4 GHz.'],
  ["SmartWatch","149","lib/images/smartwatch.png",Colors.blue,'Water Resistant	Yes Water Resistant Certificate	5ATM Scratch Resistant	Yes Meters and sensors	Heart Rate Monitor, SpO2 (Blood Oxygen) Monitor, Blood Pressure Monitor, Calorie Count, Step Count, Sleep Monitor Extra Features	Alarm Clock, Stopwatch, Timer, Reminder'],
  ["Mouse","15","lib/images/mouse.png",Colors.green,'This ultra-slim optical mouse of Nedis is compact and fits comfortably in your hand. Just plug the cable of your mouse to the USB port of your PC or notebook to enjoy fast, smooth and accurate navigation. With a resolution of 1000 dpi, even the smallest movements are registered. Due to the ergonomic design, this mouse is appropriate for both left- and right-handed users. The Nedis ultra-slim optical mouse comes in four different colours.'],
  ["HeadPhone","59","lib/images/headphone.png",Colors.grey,'Double-ear standard headset. High quality dynamic cardioid microphone. High ambient-noise attenuation headphones. Microphone: 300Hz – 20kHz frequency response. Headphone: 40Hz – 20kHz frequency response. Cushioned with soft leatherette padding. Flexible gooseneck microphone positioning.'],
  
 ];